# Generated by Django 4.2.2 on 2023-06-29 07:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import paw_prints_app.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), paw_prints_app.accounts.validators.name_contains_only_letters])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), paw_prints_app.accounts.validators.name_contains_only_letters])),
                ('profile_picture', models.ImageField(upload_to='images', validators=[paw_prints_app.accounts.validators.validate_file_size])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pet')},
            },
        ),
    ]
