# Generated by Django 4.2.2 on 2023-07-03 06:23

import django.core.validators
from django.db import migrations, models
import paw_prints_app.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_userfavorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2), paw_prints_app.accounts.validators.name_contains_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2), paw_prints_app.accounts.validators.name_contains_only_letters]),
        ),
    ]
