# Generated by Django 4.2.5 on 2023-10-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='town',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
