# Generated by Django 4.2.2 on 2023-06-29 10:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoComment',
            new_name='Comment',
        ),
    ]
