# Generated by Django 4.2.5 on 2023-09-16 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_photocomment_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
