# Generated by Django 4.2.2 on 2023-06-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='pet_category',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
