# Generated by Django 4.2.2 on 2023-06-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_breed_pet_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(),
        ),
    ]
