# Generated by Django 4.2.2 on 2023-07-03 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0005_pet_adopted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adopted_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
