# Generated by Django 4.2.5 on 2023-09-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_adopted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='related_pets',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_breeds', to='pets.pet'),
        ),
    ]
