# Generated by Django 4.2.5 on 2023-09-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_breed_related_pets'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='contact_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
